/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stock_ChanlunXLib */

#ifndef _Included_com_stock_ChanlunXLib
#define _Included_com_stock_ChanlunXLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stock_ChanlunXLib
 * Method:    Func1
 * Signature: (I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_stock_ChanlunXLib_Func1
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_stock_ChanlunXLib
 * Method:    Func2
 * Signature: (I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_stock_ChanlunXLib_Func2
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_stock_ChanlunXLib
 * Method:    Func3
 * Signature: (I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_stock_ChanlunXLib_Func3
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_stock_ChanlunXLib
 * Method:    Func4
 * Signature: (I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_stock_ChanlunXLib_Func4
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_stock_ChanlunXLib
 * Method:    Func5
 * Signature: (I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_stock_ChanlunXLib_Func5
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_stock_ChanlunXLib
 * Method:    Func6
 * Signature: (I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_stock_ChanlunXLib_Func6
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_stock_ChanlunXLib
 * Method:    Func7
 * Signature: (I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_stock_ChanlunXLib_Func7
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_stock_ChanlunXLib
 * Method:    Func8
 * Signature: (I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_stock_ChanlunXLib_Func8
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_stock_ChanlunXLib
 * Method:    Func9
 * Signature: (I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_com_stock_ChanlunXLib_Func9
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
